services:
  - type: web
    name: reciclaje-inteligente
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    runtime: python3.9
